version: "3"

services:
     
  redis:
    container_name: redis
    image: redis:5
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    networks:
      - jjw

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: coupon
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    networks:
      - jjw
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jjw:
    driver: bridge
